language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

services:
  - mysql

before_install:
  - nvm install 5.1

before_script:
  - mysql -e 'create database symfony_test;'
  - export DB_DATABASE=symfony_test
  - export DB_USERNAME=travis
  - export DB_PASSWORD=
  - composer self-update
  - composer install --no-interaction

#script:
#  - vendor/bin/phpunit
