ais_bundle_doctor:
    resource: "@AisBundleDoctorBundle/Resources/config/routing.yml"
    prefix:   /

ais_patient:
    resource: "@AisPatientBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

api:
    resource: "@ApiBundle/Controller/V1/"
    type:     annotation
    prefix:   /api/v1

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /app
